version: "2.1"
services:
  wikijs:
    image: lscr.io/linuxserver/wikijs:latest
    container_name: wikijs
    environment:
      - PUID=${WIKI_UID}
      - PGID=${WIKI_GID}
      - TZ=${WIKI_TZ}
      - DB_TYPE=sqlite
    volumes:
      - ${WIKI_CONFIG_VOL}:/config
      - ${WIKI_DATA_VOL}:/data
    ports:
      - 3000:3000
    restart: unless-stopped
