# Taken from podman specific article:
# https://www.procustodibus.com/blog/2022/10/wireguard-in-podman/

version: '3'
services:
  wireguard:
    image: docker.io/procustodibus/wireguard
    cap_add:
      - NET_ADMIN
    ports:
      - 51823:51823/udp
    sysctls:
      - net.ipv4.conf.all.forwarding=1
    volumes:
      - ./conf:${CONFIG_PATH}:Z
